services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_backend_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./database:/app/database
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
      - APP_NAME=Backend
      - APP_ENV=local
      - APP_KEY=base64:YrjNfvnnL5E7NJjhVSGhlbQYLu1BO8b78+EbzlBBOnU=
      - APP_DEBUG=false
      - APP_URL=http://127.0.0.1:8000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend:
    driver: bridge
